version: "3.3"

services:
  api_db:
    image: postgres:14.0-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./.tmp/api_db:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  e2e_db:
    image: postgres:14.0-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d

  api:
    image: node:14-alpine
    depends_on:
      - api_db
    restart: unless-stopped
    working_dir: /usr/src/app
    environment:
      - PORT=${PORT}
      - INSPECTOR_PORT=${INSPECTOR_PORT}
      - AUTH_TYPE=${AUTH_TYPE}
      - AUTH_USERNAME=${AUTH_USERNAME}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - DB_HOST=api_db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./api:/usr/src/app
    ports:
      - ${PORT}:${PORT}
      - ${INSPECTOR_PORT}:9229
    command: sh -c "npm install && npm run start"

  e2e_api:
    image: node:14-alpine
    depends_on:
      - e2e_db
    working_dir: /usr/src/app
    environment:
      - PORT=${PORT}
      - INSPECTOR_PORT=${INSPECTOR_PORT}
      - AUTH_TYPE=${AUTH_TYPE}
      - AUTH_USERNAME=${AUTH_USERNAME}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - DB_HOST=e2e_db
      - DB_NAME=test
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./api:/usr/src/app
    command: sh -c "npm install && npm run start"

  e2e_runner:
    image: node:14-alpine
    depends_on:
      - e2e_api
    working_dir: /usr/src/app
    environment:
      - DB_NAME=${DB_NAME}
      - DATABASE_URL=postgres://postgres:${DB_ROOT_PASSWORD}@e2e_db/postgres
    volumes:
      - ./e2e:/usr/src/app

  dbmigrate:
    image: dbmigrate/db-migrate:v0.1-all
    depends_on:
      - api_db
      - e2e_db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db/migrations/database.json:/home/node/database.json
      - ./db/migrations:/home/node/migrations

