version: "3.3"

services:
  postgres:
    image: postgres:14.0-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./.tmp/postgres:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  dbmigrate:
    image: dbmigrate/db-migrate:v0.1-all
    depends_on:
      - postgres
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
    volumes:
      - ./db/migrations/database.json:/home/node/database.json
      - ./db/migrations:/home/node/migrations

  nodeapi:
    image: node:14-alpine
    depends_on:
      - postgres
    restart: unless-stopped
    working_dir: /usr/src/app
    environment:
      - PORT=${PORT}
      - INSPECTOR_PORT=${INSPECTOR_PORT}
      - AUTH_TYPE=${AUTH_TYPE}
      - AUTH_USERNAME=${AUTH_USERNAME}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - DATABASE_URL=postgres://$DB_USER:$DB_PASSWORD@postgres/$DB_NAME
    volumes:
      - ./nodeapi:/usr/src/app
    ports:
      - ${PORT}:${PORT}
      - ${INSPECTOR_PORT}:9229
    command: sh -c "npm install && npm run start"
